version: '3'
services:
  validator-1:
    hostname: validator-1
    image: ${QUORUM_IMAGE}
    ports:
      - '30305:30303/udp'
      - '30305:30303/tcp'
      - '8547:8545'
    entrypoint:
      - /bin/sh
      - -c
      - chmod 755 /importData/run_geth.sh && /importData/run_geth.sh ${PRIV_KEY_1}
    networks:
      app_net:
        ipv4_address: 172.16.239.11
    restart: "no"
    volumes:
      - ./:/importData
    environment:
      - PRIVATE_CONFIG=ignore
  validator-2:
    hostname: validator-2
    image: ${QUORUM_IMAGE}
    ports:
      - '30306:30303/udp'
      - '30306:30303/tcp'
      - '8548:8545'
    entrypoint:
      - /bin/sh
      - -c
      - chmod 755 /importData/run_geth.sh && /importData/run_geth.sh ${PRIV_KEY_2}
    networks:
      app_net:
        ipv4_address: 172.16.239.12
    restart: "no"
    volumes:
      - ./:/importData
    environment:
      - PRIVATE_CONFIG=ignore
  validator-3:
    hostname: validator-3
    image: ${QUORUM_IMAGE}
    ports:
      - '30307:30303/udp'
      - '30307:30303/tcp'
      - '8549:8545'
    entrypoint:
      - /bin/sh
      - -c
      - chmod 755 /importData/run_geth.sh && /importData/run_geth.sh ${PRIV_KEY_3}
    networks:
      app_net:
        ipv4_address: 172.16.239.13
    restart: "no"
    volumes:
      - ./:/importData
    environment:
      - PRIVATE_CONFIG=ignore
  validator-4:
    hostname: validator-4
    image: ${QUORUM_IMAGE}
    ports:
      - '30308:30303/udp'
      - '30308:30303/tcp'
      - '8550:8545'
    entrypoint:
      - /bin/sh
      - -c
      - chmod 755 /importData/run_geth.sh && /importData/run_geth.sh ${PRIV_KEY_4}
    networks:
      app_net:
        ipv4_address: 172.16.239.14
    restart: "no"
    volumes:
      - ./:/importData
    environment:
      - PRIVATE_CONFIG=ignore  
  validator-5:
    hostname: validator-5
    image: ${QUORUM_IMAGE}
    ports:
      - '30309:30303/udp'
      - '30309:30303/tcp'
      - '8551:8545'
    entrypoint:
      - /bin/sh
      - -c
      - chmod 755 /importData/run_geth.sh && /importData/run_geth.sh ${PRIV_KEY_5}
    networks:
      app_net:
        ipv4_address: 172.16.239.15
    restart: "no"
    volumes:
      - ./:/importData
    environment:
      - PRIVATE_CONFIG=ignore
  besu-node-0:
    hostname: besu-0
    image: ${BESU_IMAGE}
    ports:
      - '30303:30303/udp'
      - '30303:30303/tcp'
      - '8545:8545'
    entrypoint:
      - /bin/sh  
    command: 
      - -c
      - chmod 755 /eth/run_besu.sh && /eth/run_besu.sh ${PRIV_KEY_6}
    networks:
      app_net:
        ipv4_address: 172.16.239.16
    restart: "no"
    volumes:
      - ./:/eth
networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.239.0/24
